#!/usr/bin/perl -T
use strict;
use warnings;

my %el_hash;
my $elev;

while (<>) {
	chomp;
	my ($x, $y, $a, $alt, $b) = split;
	$el_hash{$alt}++ if ($alt > 300 && $alt < 700);
}

foreach $elev (sort keys %el_hash) {
	printf "%.1f m\t%d\n", $elev, $el_hash{$elev};
}
