#!/bin/sh

HOME="/import/home/ghz"
GPSP="$HOME/projects/gps"
GPS_MA="$GPSP/data/gps_alt_monthly_averages"

GPS_ALT_TEMP_0="$(mktemp /tmp/gps_alt.XXXXXXXXXXXXX)"
GPS_ALT_TEMP_1="$(mktemp /tmp/gps_alt.XXXXXXXXXXXXX)"
GPS_ALT_TEMP_HIST="$(mktemp /tmp/gps_alt.XXXXXXXXXXXXX)"
GATH456="${GPS_ALT_TEMP_HIST}.450-600"
GATH550="${GPS_ALT_TEMP_HIST}.500-550"
GATH523="${GPS_ALT_TEMP_HIST}.520-530"

cat $GPSP/data/*/gps_alt.day.avg.* > "$GPS_ALT_TEMP_0"
gnuplot -e "ALTF='$GPS_ALT_TEMP_0';ALTF_MA='$GPS_MA'" "$GPSP/gps.gnuplot"
rm "${GPS_ALT_TEMP_0}"

cat $GPSP/data/*/gps_alt.dat.* > "$GPS_ALT_TEMP_1"
gnuplot -e "BOXF='$GPS_ALT_TEMP_1'" "$GPSP/boxplot.gnuplot"

$GPSP/alt_hist_gen "$GPS_ALT_TEMP_1" > "$GPS_ALT_TEMP_HIST"
egrep "^4[56789][0-9]\.[0-9]|^5[0-9]{2}\.[0-9]" "$GPS_ALT_TEMP_HIST" > "${GATH456}"
egrep "^5[01234][0-9]\.[0-9]" "$GPS_ALT_TEMP_HIST" > "${GATH550}"
egrep "^5[2][0-9]\.[0-9]" "$GPS_ALT_TEMP_HIST" > "${GATH523}"
gnuplot -e "ALT_HIST='$GPS_ALT_TEMP_HIST'; AH_456='$GATH456'; AH_550='$GATH550'; AH_523='$GATH523'" "$GPSP/alt_hist.gnuplot"

rm "${GPS_ALT_TEMP_1}" "${GPS_ALT_TEMP_HIST}" "${GATH456}" "${GATH550}" "${GATH523}"
