#!/bin/sh

HOME="/import/home/ghz"
GPSP="$HOME/projects/gps"
GPS_MA="$GPSP/data/gps_alt_monthly_averages"
GPS_STS="$GPSP/data/gps_alt_stats"
PAT0="^2([0-9]{13})\tavg alt: [0-9]{3}.[0-9] m\tavg evp: [0-9]{1,3}.[0-9] m$"

GPS_ALT_TEMP_0="$(mktemp /tmp/gps_alt.XXXXXXXXXXXXX)"
GPS_ALT_TEMP_1="$(mktemp /tmp/gps_alt.XXXXXXXXXXXXX)"
GPS_ALT_TEMP_HIST="$(mktemp /tmp/gps_alt.XXXXXXXXXXXXX)"

cat $GPSP/data/*/gps_alt.day.avg.* > "$GPS_ALT_TEMP_0"
gnuplot -e "ALTF='$GPS_ALT_TEMP_0';ALTF_MA='$GPS_MA'" "$GPSP/gps.gnuplot"
rm "${GPS_ALT_TEMP_0}"

cat $GPSP/data/*/gps_alt.dat.* | grep -aP "$PAT0" > "$GPS_ALT_TEMP_1"
gnuplot -e "BOXF='$GPS_ALT_TEMP_1'; OUT_DIR='$GPSP/plots'; COL=4;" "$GPSP/boxplot.gnuplot" 2> "$GPS_STS"

REC="$(grep 'Records:' $GPS_STS | awk '{print $2}')"
MEAN="$(grep 'Mean:' $GPS_STS | awk '{printf("%.2f\n",$2)}')"
MED="$(grep 'Median:' $GPS_STS | awk '{printf("%.2f\n",$2)}')"
TS="$(date -u "+%F %T%Z")"

sed "s/AAAAA/${REC}/; s/MMMMM/${MEAN}/; s/DDDDD/${MED}/; s/TTTTT/${TS}/" "$GPSP/gps_el.html.plate" > "$GPSP/gps_el.html"

$GPSP/alt_hist_gen "$GPS_ALT_TEMP_1" > "$GPS_ALT_TEMP_HIST"
gnuplot -e "ALT_HIST='$GPS_ALT_TEMP_HIST'; OUT_DIR='$GPSP/plots';" "$GPSP/alt_hist.gnuplot"

rm "${GPS_ALT_TEMP_1}" "${GPS_ALT_TEMP_HIST}"
