#!/usr/bin/python3

# thanks again to Adafruit and all their wonderful boards, libs and docs.
#
# docs:
# https://learn.adafruit.com/adafruit-mini-gps-pa1010d-module?view=all
#
# datasheet:
# https://cdn-learn.adafruit.com/assets/assets/000/084/295/original/CD_PA1010D_Datasheet_v.03.pdf

import time, board, busio, adafruit_gps
i2c = board.I2C()
gps = adafruit_gps.GPS_GtopI2C(i2c)

gps.send_command(b'PMTK314,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0')
gps.send_command(b'PMTK220,1000')

time1 = time0 = time.monotonic()
while True:
	time1 = time.monotonic()
	if gps.update(): 
		to = gps.timestamp_utc
		if gps.has_fix and to and to.tm_year and ((time1 - time0) > 1):
			time0 = time.monotonic()
			TS = "{}-{:02}-{:02}T{:02}:{:02}:{:02}Z".format(
				to.tm_year, to.tm_mon, to.tm_mday,
				to.tm_hour, to.tm_min, to.tm_sec)
			print(TS, end = "\t")
	
			alt = gps.altitude_m
			if alt is not None:
				print(gps.altitude_m, "m", end = "\t")

			vdop = gps.vdop
			if vdop is not None:
				print("{:.2f} vdop".format(vdop), end = "\t")

			# this has so far always returned 47.9 m
			# geo_h = gps.height_geoid
			# if geo_h is not None:
			# 	print("{} m geoid height".format(gps.height_geoid), end = "\t")

			sats = gps.satellites
			if sats is not None:
				print(sats, "sats")

	time.sleep(0.02)
