#!/usr/bin/env python
# -*- coding: utf-8 -*-
# this code indented with actual 0x09 tabs

from gps import *
import time

gps_inst = gps(mode=WATCH_ENABLE|WATCH_NEWSTYLE)

vdop = alt = sat_count = epv = gtime = gmode = 0
alt_lst = []

while True:
	report = gps_inst.next()
	# print report	# for debugging
	if report['class'] == 'SKY':
		sat_count = 0
		for i in report['satellites']:
			if i['used']:
				sat_count += 1
		vdop = getattr(report, 'vdop', '0.0')
	if report['class'] == 'TPV':
		alt = getattr(report, 'alt', '0.0')
		epv = getattr(report, 'epv', '0.0')
		gtime = getattr(report, 'time', '0.0')
		gmode = getattr(report, 'mode', '0.0')

	if gmode == 3 and sat_count != 0:
		print "time: %s\talt: %sm\tepv: %sm\tvdop: %s\tsat_count: %s" % (gtime, alt, epv, vdop, sat_count)
		alt_lst.append((alt, epv))
		lst_len = len(alt_lst)
		avg_alt = sum(a[0] for a in alt_lst) / lst_len
		avg_evp = sum(a[1] for a in alt_lst) / lst_len
		print "avg alt: %.1f, avg evp: %.1f" % (avg_alt, avg_evp)

	print "len: %d" % len(alt_lst)
	if len(alt_lst) > 1024:
		alt_lst.remove(alt_lst[0])
